/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PaymentMethod = IDL.Variant({
  'eth' : IDL.Null,
  'trade' : IDL.Null,
  'cash' : IDL.Null,
  'essence' : IDL.Null,
});
export const Position = IDL.Variant({
  'torwart' : IDL.Null,
  'verteidiger' : IDL.Null,
  'sturm' : IDL.Null,
  'mittelfeld' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const CardId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const InvestmentTotals = IDL.Record({
  'totalCashInvested' : IDL.Float64,
  'totalEthInvested' : IDL.Float64,
});
export const TransactionType = IDL.Variant({
  'sold' : IDL.Null,
  'tradedReceived' : IDL.Null,
  'forSale' : IDL.Null,
  'tradedGiven' : IDL.Null,
});
export const TradeTransaction = IDL.Record({
  'givenCards' : IDL.Vec(CardId),
  'receivedCards' : IDL.Vec(CardId),
});
export const Card = IDL.Record({
  'id' : CardId,
  'age' : IDL.Nat,
  'paymentMethod' : PaymentMethod,
  'purchasePrice' : IDL.Float64,
  'country' : IDL.Text,
  'transactionType' : TransactionType,
  'purchaseDate' : IDL.Opt(Time),
  'owner' : IDL.Principal,
  'club' : IDL.Text,
  'name' : IDL.Text,
  'tradeReference' : IDL.Opt(TradeTransaction),
  'season' : IDL.Text,
  'discountPercent' : IDL.Float64,
  'version' : IDL.Text,
  'league' : IDL.Text,
  'notes' : IDL.Text,
  'salePrice' : IDL.Opt(IDL.Float64),
  'rarity' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'position' : Position,
  'saleDate' : IDL.Opt(Time),
});
export const CardWithUser = IDL.Record({
  'cards' : IDL.Vec(Card),
  'user' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'profileImage' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
});
export const ChangeAction = IDL.Variant({
  'updateSalePrice' : IDL.Null,
  'trade' : IDL.Null,
  'addCard' : IDL.Null,
  'markSold' : IDL.Null,
  'deleteCard' : IDL.Null,
  'revertTrade' : IDL.Null,
  'editCard' : IDL.Null,
});
export const ChangeHistoryEntry = IDL.Record({
  'action' : ChangeAction,
  'summary' : IDL.Text,
  'timestamp' : Time,
  'cardIds' : IDL.Vec(CardId),
});
export const PortfolioSnapshot = IDL.Record({
  'holdBalance' : IDL.Float64,
  'totalInvested' : IDL.Float64,
  'investmentTotals' : InvestmentTotals,
  'allCards' : IDL.Vec(Card),
  'portfolioTotal' : IDL.Float64,
  'totalReturns' : IDL.Float64,
  'totalBalance' : IDL.Float64,
  'totalReturnBalance' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCard' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        PaymentMethod,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Position,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [CardId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'backfillHistoryEntries' : IDL.Func([], [], []),
  'calculateInvestmentTotals' : IDL.Func([], [InvestmentTotals], ['query']),
  'calculateTotalBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'calculateTotalInvested' : IDL.Func([], [IDL.Float64], ['query']),
  'calculateTotalReturns' : IDL.Func([], [IDL.Float64], ['query']),
  'deleteCard' : IDL.Func([CardId], [], []),
  'getAllCardsForUser' : IDL.Func([], [IDL.Vec(Card)], ['query']),
  'getAllCardsWithUser' : IDL.Func([IDL.Principal], [CardWithUser], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChangeHistory' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(ChangeHistoryEntry)],
      ['query'],
    ),
  'getPortfolioSnapshot' : IDL.Func([], [PortfolioSnapshot], ['query']),
  'getSoldCardBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCardAsSold' : IDL.Func([CardId, IDL.Float64, Time], [], []),
  'recordTradeTransaction' : IDL.Func(
      [IDL.Vec(CardId), IDL.Vec(CardId)],
      [],
      [],
    ),
  'revertTradeTransaction' : IDL.Func([CardId, TradeTransaction], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCard' : IDL.Func(
      [
        CardId,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        PaymentMethod,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Position,
        IDL.Opt(Time),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSalePrice' : IDL.Func([CardId, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PaymentMethod = IDL.Variant({
    'eth' : IDL.Null,
    'trade' : IDL.Null,
    'cash' : IDL.Null,
    'essence' : IDL.Null,
  });
  const Position = IDL.Variant({
    'torwart' : IDL.Null,
    'verteidiger' : IDL.Null,
    'sturm' : IDL.Null,
    'mittelfeld' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const CardId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const InvestmentTotals = IDL.Record({
    'totalCashInvested' : IDL.Float64,
    'totalEthInvested' : IDL.Float64,
  });
  const TransactionType = IDL.Variant({
    'sold' : IDL.Null,
    'tradedReceived' : IDL.Null,
    'forSale' : IDL.Null,
    'tradedGiven' : IDL.Null,
  });
  const TradeTransaction = IDL.Record({
    'givenCards' : IDL.Vec(CardId),
    'receivedCards' : IDL.Vec(CardId),
  });
  const Card = IDL.Record({
    'id' : CardId,
    'age' : IDL.Nat,
    'paymentMethod' : PaymentMethod,
    'purchasePrice' : IDL.Float64,
    'country' : IDL.Text,
    'transactionType' : TransactionType,
    'purchaseDate' : IDL.Opt(Time),
    'owner' : IDL.Principal,
    'club' : IDL.Text,
    'name' : IDL.Text,
    'tradeReference' : IDL.Opt(TradeTransaction),
    'season' : IDL.Text,
    'discountPercent' : IDL.Float64,
    'version' : IDL.Text,
    'league' : IDL.Text,
    'notes' : IDL.Text,
    'salePrice' : IDL.Opt(IDL.Float64),
    'rarity' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'position' : Position,
    'saleDate' : IDL.Opt(Time),
  });
  const CardWithUser = IDL.Record({
    'cards' : IDL.Vec(Card),
    'user' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'profileImage' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
  });
  const ChangeAction = IDL.Variant({
    'updateSalePrice' : IDL.Null,
    'trade' : IDL.Null,
    'addCard' : IDL.Null,
    'markSold' : IDL.Null,
    'deleteCard' : IDL.Null,
    'revertTrade' : IDL.Null,
    'editCard' : IDL.Null,
  });
  const ChangeHistoryEntry = IDL.Record({
    'action' : ChangeAction,
    'summary' : IDL.Text,
    'timestamp' : Time,
    'cardIds' : IDL.Vec(CardId),
  });
  const PortfolioSnapshot = IDL.Record({
    'holdBalance' : IDL.Float64,
    'totalInvested' : IDL.Float64,
    'investmentTotals' : InvestmentTotals,
    'allCards' : IDL.Vec(Card),
    'portfolioTotal' : IDL.Float64,
    'totalReturns' : IDL.Float64,
    'totalBalance' : IDL.Float64,
    'totalReturnBalance' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCard' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          PaymentMethod,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Position,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [CardId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'backfillHistoryEntries' : IDL.Func([], [], []),
    'calculateInvestmentTotals' : IDL.Func([], [InvestmentTotals], ['query']),
    'calculateTotalBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'calculateTotalInvested' : IDL.Func([], [IDL.Float64], ['query']),
    'calculateTotalReturns' : IDL.Func([], [IDL.Float64], ['query']),
    'deleteCard' : IDL.Func([CardId], [], []),
    'getAllCardsForUser' : IDL.Func([], [IDL.Vec(Card)], ['query']),
    'getAllCardsWithUser' : IDL.Func(
        [IDL.Principal],
        [CardWithUser],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChangeHistory' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(ChangeHistoryEntry)],
        ['query'],
      ),
    'getPortfolioSnapshot' : IDL.Func([], [PortfolioSnapshot], ['query']),
    'getSoldCardBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCardAsSold' : IDL.Func([CardId, IDL.Float64, Time], [], []),
    'recordTradeTransaction' : IDL.Func(
        [IDL.Vec(CardId), IDL.Vec(CardId)],
        [],
        [],
      ),
    'revertTradeTransaction' : IDL.Func([CardId, TradeTransaction], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCard' : IDL.Func(
        [
          CardId,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          PaymentMethod,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Position,
          IDL.Opt(Time),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSalePrice' : IDL.Func([CardId, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };