/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Card {
  'id' : CardId,
  'age' : bigint,
  'paymentMethod' : PaymentMethod,
  'purchasePrice' : number,
  'country' : string,
  'transactionType' : TransactionType,
  'purchaseDate' : [] | [Time],
  'owner' : Principal,
  'club' : string,
  'name' : string,
  'tradeReference' : [] | [TradeTransaction],
  'season' : string,
  'discountPercent' : number,
  'version' : string,
  'league' : string,
  'notes' : string,
  'salePrice' : [] | [number],
  'rarity' : string,
  'image' : [] | [ExternalBlob],
  'position' : Position,
  'saleDate' : [] | [Time],
}
export type CardId = bigint;
export interface CardWithUser { 'cards' : Array<Card>, 'user' : Principal }
export type ExternalBlob = Uint8Array;
export interface InvestmentTotals {
  'totalCashInvested' : number,
  'totalEthInvested' : number,
}
export type PaymentMethod = { 'eth' : null } |
  { 'trade' : null } |
  { 'cash' : null } |
  { 'essence' : null };
export type Position = { 'torwart' : null } |
  { 'verteidiger' : null } |
  { 'sturm' : null } |
  { 'mittelfeld' : null };
export type Time = bigint;
export interface TradeTransaction {
  'givenCards' : Array<CardId>,
  'receivedCards' : Array<CardId>,
}
export interface TransactionGroup {
  'sold' : Array<Card>,
  'tradedReceived' : Array<Card>,
  'forSale' : Array<Card>,
  'tradedGiven' : Array<Card>,
}
export interface TransactionSummary {
  'tradedGivenCount' : bigint,
  'forSaleCount' : bigint,
  'tradedReceivedCount' : bigint,
  'soldCount' : bigint,
}
export type TransactionType = { 'sold' : null } |
  { 'tradedReceived' : null } |
  { 'forSale' : null } |
  { 'tradedGiven' : null };
export interface UserProfile {
  'profileImage' : [] | [ExternalBlob],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCard' : ActorMethod<
    [
      string,
      string,
      number,
      number,
      PaymentMethod,
      string,
      string,
      string,
      bigint,
      string,
      string,
      Position,
      [] | [Time],
      string,
      [] | [ExternalBlob],
    ],
    CardId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateInvestmentTotals' : ActorMethod<[], InvestmentTotals>,
  'calculateTotalBalance' : ActorMethod<[], number>,
  'calculateTotalInvested' : ActorMethod<[], number>,
  'calculateTotalReturns' : ActorMethod<[], number>,
  'countCraftedCards' : ActorMethod<[], bigint>,
  'deleteCard' : ActorMethod<[CardId], undefined>,
  'getAllCardsForUser' : ActorMethod<[], Array<Card>>,
  'getAllCardsForUserRPC' : ActorMethod<[Principal], Array<Card>>,
  'getAllCardsWithUser' : ActorMethod<[Principal], CardWithUser>,
  'getAllCraftedCards' : ActorMethod<
    [],
    { 'cards' : Array<Card>, 'count' : bigint }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCardById' : ActorMethod<[CardId], [] | [Card]>,
  'getCardsByTransactionType' : ActorMethod<[TransactionType], Array<Card>>,
  'getCraftedCards' : ActorMethod<[], Array<Card>>,
  'getCraftedCardsWithBalance' : ActorMethod<
    [],
    { 'balance' : bigint, 'cards' : Array<Card> }
  >,
  'getSoldCardBalance' : ActorMethod<[], number>,
  'getSoldCards' : ActorMethod<[Principal], Array<Card>>,
  'getTradeSummary' : ActorMethod<
    [],
    {
      'totalReceived' : bigint,
      'totalCards' : bigint,
      'givenCards' : Array<Card>,
      'totalGiven' : bigint,
      'receivedCards' : Array<Card>,
    }
  >,
  'getTransactionGroups' : ActorMethod<[], TransactionGroup>,
  'getTransactionSummary' : ActorMethod<[], TransactionSummary>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getValidCardIds' : ActorMethod<[], Array<CardId>>,
  'initializeDefaultCardForUsers' : ActorMethod<
    [Principal, Principal],
    undefined
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markCardAsSold' : ActorMethod<[CardId, number, [] | [Time]], undefined>,
  'markCardAsSoldById' : ActorMethod<[CardId, number, [] | [Time]], undefined>,
  'recordTradeTransaction' : ActorMethod<
    [Array<CardId>, Array<CardId>],
    undefined
  >,
  'revertTradeTransaction' : ActorMethod<[Array<CardId>], undefined>,
  'saveBatchCards' : ActorMethod<[Array<Card>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'swapCardIds' : ActorMethod<[Principal, Principal], undefined>,
  'transferCardOwnership' : ActorMethod<[CardId, Principal], undefined>,
  'updateCard' : ActorMethod<
    [
      CardId,
      string,
      string,
      number,
      number,
      PaymentMethod,
      string,
      string,
      string,
      bigint,
      string,
      string,
      Position,
      [] | [Time],
      string,
    ],
    undefined
  >,
  'updateCardTransactionType' : ActorMethod<
    [CardId, TransactionType],
    undefined
  >,
  'updateSalePrice' : ActorMethod<[CardId, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];