/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Card {
    id: CardId;
    age: bigint;
    paymentMethod: PaymentMethod;
    purchasePrice: number;
    country: string;
    transactionType: TransactionType;
    purchaseDate?: Time;
    owner: Principal;
    club: string;
    name: string;
    tradeReference?: TradeTransaction;
    season: string;
    discountPercent: number;
    version: string;
    league: string;
    notes: string;
    salePrice?: number;
    rarity: string;
    image?: ExternalBlob;
    position: Position;
    saleDate?: Time;
}
export type Time = bigint;
export interface InvestmentTotals {
    totalCashInvested: number;
    totalEthInvested: number;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TradeTransaction {
    givenCards: Array<CardId>;
    receivedCards: Array<CardId>;
}
export interface CardWithUser {
    cards: Array<Card>;
    user: Principal;
}
export interface PortfolioSnapshot {
    holdBalance: number;
    totalInvested: number;
    investmentTotals: InvestmentTotals;
    allCards: Array<Card>;
    portfolioTotal: number;
    totalReturns: number;
    totalBalance: number;
    totalReturnBalance: number;
}
export type CardId = bigint;
export interface UserProfile {
    profileImage?: ExternalBlob;
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum PaymentMethod {
    eth = "eth",
    trade = "trade",
    cash = "cash",
    essence = "essence"
}
export enum Position {
    torwart = "torwart",
    verteidiger = "verteidiger",
    sturm = "sturm",
    mittelfeld = "mittelfeld"
}
export enum TransactionType {
    sold = "sold",
    tradedReceived = "tradedReceived",
    forSale = "forSale",
    tradedGiven = "tradedGiven"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCard(name: string, rarity: string, purchasePrice: number, discountPercent: number, paymentMethod: PaymentMethod, country: string, league: string, club: string, age: bigint, version: string, season: string, position: Position, purchaseDate: Time | null, notes: string, image: ExternalBlob | null): Promise<CardId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculateInvestmentTotals(): Promise<InvestmentTotals>;
    calculateTotalBalance(): Promise<number>;
    calculateTotalInvested(): Promise<number>;
    calculateTotalReturns(): Promise<number>;
    deleteCard(cardId: CardId): Promise<void>;
    getAllCardsForUser(): Promise<Array<Card>>;
    getAllCardsWithUser(user: Principal): Promise<CardWithUser>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPortfolioSnapshot(): Promise<PortfolioSnapshot>;
    getSoldCardBalance(): Promise<number>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCard(cardId: CardId, name: string, rarity: string, purchasePrice: number, discountPercent: number, paymentMethod: PaymentMethod, country: string, league: string, club: string, age: bigint, version: string, season: string, position: Position, purchaseDate: Time | null, notes: string): Promise<void>;
    updateSalePrice(cardId: CardId, newSalePrice: number): Promise<void>;
}
import type { Card as _Card, CardId as _CardId, CardWithUser as _CardWithUser, ExternalBlob as _ExternalBlob, InvestmentTotals as _InvestmentTotals, PaymentMethod as _PaymentMethod, PortfolioSnapshot as _PortfolioSnapshot, Position as _Position, Time as _Time, TradeTransaction as _TradeTransaction, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCard(arg0: string, arg1: string, arg2: number, arg3: number, arg4: PaymentMethod, arg5: string, arg6: string, arg7: string, arg8: bigint, arg9: string, arg10: string, arg11: Position, arg12: Time | null, arg13: string, arg14: ExternalBlob | null): Promise<CardId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCard(arg0, arg1, arg2, arg3, to_candid_PaymentMethod_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10, to_candid_Position_n10(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg12), arg13, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg14));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCard(arg0, arg1, arg2, arg3, to_candid_PaymentMethod_n8(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10, to_candid_Position_n10(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg12), arg13, await to_candid_opt_n13(this._uploadFile, this._downloadFile, arg14));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculateInvestmentTotals(): Promise<InvestmentTotals> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateInvestmentTotals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateInvestmentTotals();
            return result;
        }
    }
    async calculateTotalBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalBalance();
            return result;
        }
    }
    async calculateTotalInvested(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalInvested();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalInvested();
            return result;
        }
    }
    async calculateTotalReturns(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.calculateTotalReturns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculateTotalReturns();
            return result;
        }
    }
    async deleteCard(arg0: CardId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCard(arg0);
            return result;
        }
    }
    async getAllCardsForUser(): Promise<Array<Card>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCardsForUser();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCardsForUser();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCardsWithUser(arg0: Principal): Promise<CardWithUser> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCardsWithUser(arg0);
                return from_candid_CardWithUser_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCardsWithUser(arg0);
            return from_candid_CardWithUser_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolioSnapshot(): Promise<PortfolioSnapshot> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolioSnapshot();
                return from_candid_PortfolioSnapshot_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolioSnapshot();
            return from_candid_PortfolioSnapshot_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSoldCardBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoldCardBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoldCardBalance();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCard(arg0: CardId, arg1: string, arg2: string, arg3: number, arg4: number, arg5: PaymentMethod, arg6: string, arg7: string, arg8: string, arg9: bigint, arg10: string, arg11: string, arg12: Position, arg13: Time | null, arg14: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentMethod_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, arg11, to_candid_Position_n10(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg13), arg14);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCard(arg0, arg1, arg2, arg3, arg4, to_candid_PaymentMethod_n8(this._uploadFile, this._downloadFile, arg5), arg6, arg7, arg8, arg9, arg10, arg11, to_candid_Position_n10(this._uploadFile, this._downloadFile, arg12), to_candid_opt_n12(this._uploadFile, this._downloadFile, arg13), arg14);
            return result;
        }
    }
    async updateSalePrice(arg0: CardId, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalePrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalePrice(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_CardWithUser_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CardWithUser): Promise<CardWithUser> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Card_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Card): Promise<Card> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_PaymentMethod_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_PortfolioSnapshot_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PortfolioSnapshot): Promise<PortfolioSnapshot> {
    return await from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Position_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TradeTransaction]): TradeTransaction | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CardId;
    age: bigint;
    paymentMethod: _PaymentMethod;
    purchasePrice: number;
    country: string;
    transactionType: _TransactionType;
    purchaseDate: [] | [_Time];
    owner: Principal;
    club: string;
    name: string;
    tradeReference: [] | [_TradeTransaction];
    season: string;
    discountPercent: number;
    version: string;
    league: string;
    notes: string;
    salePrice: [] | [number];
    rarity: string;
    image: [] | [_ExternalBlob];
    position: _Position;
    saleDate: [] | [_Time];
}): Promise<{
    id: CardId;
    age: bigint;
    paymentMethod: PaymentMethod;
    purchasePrice: number;
    country: string;
    transactionType: TransactionType;
    purchaseDate?: Time;
    owner: Principal;
    club: string;
    name: string;
    tradeReference?: TradeTransaction;
    season: string;
    discountPercent: number;
    version: string;
    league: string;
    notes: string;
    salePrice?: number;
    rarity: string;
    image?: ExternalBlob;
    position: Position;
    saleDate?: Time;
}> {
    return {
        id: value.id,
        age: value.age,
        paymentMethod: from_candid_PaymentMethod_n20(_uploadFile, _downloadFile, value.paymentMethod),
        purchasePrice: value.purchasePrice,
        country: value.country,
        transactionType: from_candid_TransactionType_n22(_uploadFile, _downloadFile, value.transactionType),
        purchaseDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.purchaseDate)),
        owner: value.owner,
        club: value.club,
        name: value.name,
        tradeReference: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.tradeReference)),
        season: value.season,
        discountPercent: value.discountPercent,
        version: value.version,
        league: value.league,
        notes: value.notes,
        salePrice: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.salePrice)),
        rarity: value.rarity,
        image: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.image)),
        position: from_candid_Position_n29(_uploadFile, _downloadFile, value.position),
        saleDate: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.saleDate))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cards: Array<_Card>;
    user: Principal;
}): Promise<{
    cards: Array<Card>;
    user: Principal;
}> {
    return {
        cards: await from_candid_vec_n17(_uploadFile, _downloadFile, value.cards),
        user: value.user
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileImage: [] | [_ExternalBlob];
    name: string;
}): Promise<{
    profileImage?: ExternalBlob;
    name: string;
}> {
    return {
        profileImage: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name
    };
}
async function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    holdBalance: number;
    totalInvested: number;
    investmentTotals: _InvestmentTotals;
    allCards: Array<_Card>;
    portfolioTotal: number;
    totalReturns: number;
    totalBalance: number;
    totalReturnBalance: number;
}): Promise<{
    holdBalance: number;
    totalInvested: number;
    investmentTotals: InvestmentTotals;
    allCards: Array<Card>;
    portfolioTotal: number;
    totalReturns: number;
    totalBalance: number;
    totalReturnBalance: number;
}> {
    return {
        holdBalance: value.holdBalance,
        totalInvested: value.totalInvested,
        investmentTotals: value.investmentTotals,
        allCards: await from_candid_vec_n17(_uploadFile, _downloadFile, value.allCards),
        portfolioTotal: value.portfolioTotal,
        totalReturns: value.totalReturns,
        totalBalance: value.totalBalance,
        totalReturnBalance: value.totalReturnBalance
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eth: null;
} | {
    trade: null;
} | {
    cash: null;
} | {
    essence: null;
}): PaymentMethod {
    return "eth" in value ? PaymentMethod.eth : "trade" in value ? PaymentMethod.trade : "cash" in value ? PaymentMethod.cash : "essence" in value ? PaymentMethod.essence : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sold: null;
} | {
    tradedReceived: null;
} | {
    forSale: null;
} | {
    tradedGiven: null;
}): TransactionType {
    return "sold" in value ? TransactionType.sold : "tradedReceived" in value ? TransactionType.tradedReceived : "forSale" in value ? TransactionType.forSale : "tradedGiven" in value ? TransactionType.tradedGiven : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    torwart: null;
} | {
    verteidiger: null;
} | {
    sturm: null;
} | {
    mittelfeld: null;
}): Position {
    return "torwart" in value ? Position.torwart : "verteidiger" in value ? Position.verteidiger : "sturm" in value ? Position.sturm : "mittelfeld" in value ? Position.mittelfeld : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Card>): Promise<Array<Card>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Card_n18(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PaymentMethod_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Position_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    profileImage?: ExternalBlob;
    name: string;
}): Promise<{
    profileImage: [] | [_ExternalBlob];
    name: string;
}> {
    return {
        profileImage: value.profileImage ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.profileImage)) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): {
    torwart: null;
} | {
    verteidiger: null;
} | {
    sturm: null;
} | {
    mittelfeld: null;
} {
    return value == Position.torwart ? {
        torwart: null
    } : value == Position.verteidiger ? {
        verteidiger: null
    } : value == Position.sturm ? {
        sturm: null
    } : value == Position.mittelfeld ? {
        mittelfeld: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    eth: null;
} | {
    trade: null;
} | {
    cash: null;
} | {
    essence: null;
} {
    return value == PaymentMethod.eth ? {
        eth: null
    } : value == PaymentMethod.trade ? {
        trade: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.essence ? {
        essence: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
